version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    links:
      - api
      - db
  api:
    build: ./api
    ports:
      - "5000:5000"
    links:
      - db

  db:
    build: ./db
